x-service-aliases: &service-aliases
  extra_hosts:
    - "llama:172.21.0.2"

services:
  llm:
    build:
      context: ./src/llm
      dockerfile: Dockerfile
    container_name: llm
    command: /bin/bash -c "/scripts/start-llama-service.sh; tail -f /dev/null"
    ports:
      - "11434:11434"
    volumes:
      - ./src/llm/scripts:/scripts
    networks:
      rag-net:
        ipv4_address: 172.21.0.2
    <<: *service-aliases

networks:
  rag-net:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
