document_matching:
  # The documents read into the vector store. File extensions *with the dot* are expected.
  # Leave empty to read all files (subject to the rules in the "excluded" field).
  allowed_file_extensions: []
  # Patterns to exclude from vector store. Glob expressions are expected.
  # By default, ignore all hidden files and directories.
  # Curly brace notation is not supported for some reason...
  excluded: ["**/.*"]
document_splitter:
  # The max size in characters of each document chunk.
  chunk_size: 500
  # The overlap between each chunk in characters.
  chunk_overlap: 200